version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:14.0.2-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - run:
          command: |
            google-chrome --version
          name: check install
      - run: mvn clean test
      - run:
          name: Allure Report
          command: mvn allure:report
          when: always
      - store_test_results:
          path: target/surefire-reports/junitreports
      - store_artifacts:
          path: target/site/allure-maven-plugin
      - store_artifacts:
          path: Screenshots
orbs:
  browser-tools: circleci/browser-tools@1.1.3

workflows:
  sample:
    jobs:
      - build-and-test
