@startuml
package DriverFactory {
    class DriverFactory {
        + getBrowser() :WebDriver
        - getChromeDriver() :WebDriver
        - getFirefoxDriver() :WebDriver
        - getEdgeDriver() :WebDriver
    }
}

package Pages {
    class BasePage {
        - driver : WebDriver
        # waitUtils : WaitUtils
        + BasePage(driver:WebDriver)
        + initialWait(driver:WebDriver) :void
    }
    package Allo {
        class Cart extends BasePage {
            - cartPopup : WebElement
            - productCardsTitles : List<WebElements>
            + Cart(driver:WebDriver)
            + initialWait(driver:WebDriver) :void
            + verifyThatProductIsInCart(productName:String) :void
        }
        class ComparisonPage extends BasePage {
            - productTitles : List<WebElements>
            - compareHeaderContainer : WebElement
            + ComparisonPage(driver:WebDriver)
            + initialWait(driver:WebDriver) :void
            + isProductTitleDisplayed(productName:String) :void
        }
        class Header extends BasePage {
            - searchBar : WebElement
            - loginButton : WebElement
            - actualNameSpan : WebElement
            + Header(driver:WebDriver)
            + initialWait(driver:WebDriver) :void
            + clickLoginButton() :void
            + searchFor(searchQuery:String) :void
            + verifyName(expectedName:String) :void
        }
        class LoginAndRegistrarionPopup extends BasePage {
            - loginTabActive : WebElement
            - emailInput : WebElement
            - passwordInput : WebElement
            - submitButton : WebElement
            + LoginAndRegistrationPopup(driver:WebDriver)
            + initialWait(driver:WebDriver) :void
            + setEmailInput(email:String) :void
            + setPasswordInput(password:String) :void
            + clickSubmitButton() :void

        }
        class MainPage extends BasePage {
            - homeBannerPagination : WebElement
            + MainPage(driver:WebDriver)
            + initialWait(driver:WebDriver) :void
        }
        class ProductPage extends BasePage {
            - shippingBrandLink : WebElement
            - addToCompareButton : WebElement
            - getAddToCompareButtonActive : WebElement
            + ProductPage(driver:WebDriver)
            + initialWait(driver:WebDriver) :void
            + clickAddToCompareButtonOnMainTradePanel() :void
            + isCompareButtonActiveOnMainTradePanel() :void
        }
        class SearchResultPage extends BasePage {
            - addProductToCartButtonPattern : String
            - sortByOptionsPattern : String
            - activeViewModeButton : WebElement
            - loadingSpinner : WebElement
            - productCardsTitles : List<WebElements>
            - productCardsPrices : List<WebElements>
            - sortBySelect : WebElement
            - compareBlueButton : WebElement
            + SearchResultsPage(driver:WebDriver)
            + initialWait(driver:WebDriver) :void
            + clickCompareBlueButton() :void
            + clickAddProductToCartButton(productName:String) :void
            + clickProductTitle(productName:String) :void
            + verifyThatAllProductCardsAreContainSearchQuery(searchQuery:String) :void
            + verifyThatAllProductCardsAreSortedByPriceLowToHigh() :void
            + verifyThatAllProductCardsAreSortedByPriceHighToLow() :void
            - listOfWebElementsParseToIntArray(webElementsList:List<WebElements>) :Integer[]
            + selectSortingOption(optionName:String)
        }
    }
}

package Steps {
    package Base {
        class BaseUtil {
            - driver : WebDriver
            + getMainPage() : void
            + getDriver() : WebDriver
        }
        class BaseTest extends BaseUtil
    }
    class BrowserSteps extends BaseUtil
    class CartSteps extends BaseUtil
    class ComparisonPageSteps extends BaseUtil
    class HeaderSteps extends BaseUtil
    class LoginAndRegistrarionPopupSteps extends BaseUtil
    class MainPageSteps extends BaseUtil
    class ProductPageSteps extends BaseUtil
    class SearchResultPageSteps extends BaseUtil
}
package Utils {
    class Property {
        + public void getProperty()
    }

    class Converters
    class ScheenshotUtil
    class WaitUtils
}

Property --- BaseUtil

@enduml